"""add participants table

Revision ID: 17222039d1b7
Revises: f4088f02a49a
Create Date: 2022-03-30 13:15:29.614815

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision = '17222039d1b7'
down_revision = 'f4088f02a49a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('game_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('secret_santa_id', fastapi_users_db_sqlalchemy.GUID(), nullable=False),
    sa.Column('gift_recipient_id', fastapi_users_db_sqlalchemy.GUID(), nullable=False),
    sa.Column('preferences', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participants_game_id'), 'participants', ['game_id'], unique=False)
    op.create_index(op.f('ix_participants_gift_recipient_id'), 'participants', ['gift_recipient_id'], unique=False)
    op.create_index(op.f('ix_participants_secret_santa_id'), 'participants', ['secret_santa_id'], unique=False)
    op.create_index(op.f('ix_participants_updated_at'), 'participants', ['updated_at'], unique=False)
    op.drop_index('ix_users_is_playing', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_is_playing', 'users', ['is_playing'], unique=False)
    op.drop_index(op.f('ix_participants_updated_at'), table_name='participants')
    op.drop_index(op.f('ix_participants_secret_santa_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_gift_recipient_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_game_id'), table_name='participants')
    op.drop_table('participants')
    # ### end Alembic commands ###
