"""add fields to users table

Revision ID: bff03e1186f7
Revises: 10580b41217a
Create Date: 2022-03-29 10:44:24.582121

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'bff03e1186f7'
down_revision = '10580b41217a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE users
        ADD COLUMN is_playing BOOLEAN default FALSE NOT NULL
        AFTER last_name;
        
        ALTER TABLE users
        ADD COLUMN preferences TEXT NULL
        AFTER is_playing;
        """
    )
    op.create_index(op.f('ix_users_is_playing'), 'users', ['is_playing'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_is_playing'), table_name='users')
    op.drop_column('users', 'is_playing')
    op.drop_column('users', 'preferences')
    # ### end Alembic commands ###
