"""add preferences field

Revision ID: bff03e1186f7
Revises: 10580b41217a
Create Date: 2022-03-29 10:44:24.582121

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'bff03e1186f7'
down_revision = '10580b41217a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE users
        ADD COLUMN preferences TEXT NULL
        AFTER last_name;
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferences')
    # ### end Alembic commands ###
