"""add games table

Revision ID: f4088f02a49a
Revises: bff03e1186f7
Create Date: 2022-03-29 12:46:10.058656

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f4088f02a49a'
down_revision = 'bff03e1186f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('game_year', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('is_registration_open', sa.BOOLEAN(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('registration_opened_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('is_registration_close', sa.BOOLEAN(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('registration_closed_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_game_year'), 'games', ['game_year'], unique=True)
    op.create_index(op.f('ix_games_is_registration_close'), 'games', ['is_registration_close'], unique=False)
    op.create_index(op.f('ix_games_is_registration_open'), 'games', ['is_registration_open'], unique=False)
    op.create_index(op.f('ix_games_updated_at'), 'games', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_updated_at'), table_name='games')
    op.drop_index(op.f('ix_games_is_registration_open'), table_name='games')
    op.drop_index(op.f('ix_games_is_registration_close'), table_name='games')
    op.drop_index(op.f('ix_games_game_year'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
